### ISSUE TITLE
Texture?

### ISSUE THREAD

**Issue by SPMP2** [Refaltor77/CustomItemAPI#1]

**Comment by Refaltor77** [comment]
When you create an object items with the api, you have the texture path as a parameter.

**Comment by PiloudeDakar** [comment]
@Refaltor77 the texture needs to be in the texture pack.
It's the path or the identifier or other name ?

**Comment by Refaltor77** [comment]
Yes the texture must be present in the texture pack

**Comment by PiloudeDakar** [comment]
And for the second question ?

**Comment by Refaltor77** [comment]
This is the name of the texture defined in item_texture.json

I’m creating a simpler way to add textures.

**Comment by Willtom999** [comment]
@Refaltor77 et on met quoi dans item.json?

**Comment by PiloudeDakar** [comment]
@Willtom999 
En : You can create textures pack with all the options with https://bridge-core.app/
Fr : Tu peux créer des packs de texture avec toutes les options avec https://bridge-core.app/
