### ISSUE TITLE
Break with plugin RandomOre

### ISSUE THREAD

**Issue by DavidGlitch04** [Refaltor77/CustomItemAPI#12]
When I use pickaxe with [RandomOre](https://drive.google.com/file/d/1tYCgWzkfpncjFWxcwLg3DO5WrZo60yYj/view?usp=sharing) plugin, mining stops when randomore updates block

**Comment by Refaltor77** [comment]
Does the break come back or does the block once broken appear?

**Comment by Refaltor77** [comment]
Is fixed with 3.0.0 !
