### ISSUE TITLE
Armor issue

### ISSUE THREAD

**Issue by vkamz597** [Refaltor77/CustomItemAPI#14]
I definitely made it possible to wear it on the body, but it doesn't work. I'll upload the source code, so look at it.

new ArmorItem(new ItemIdentifier(5000, 0), "치장테스트", new ArmorTypeInfo(1, 500, ArmorInventory::SLOT_CHEST, 1), "iron")

**Comment by Refaltor77** [comment]
Hello, yes bug my summer report, I would soon create a new version fixed.

**Comment by Refaltor77** [comment]
Is fixed with 3.0.0 !
