### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ItsRealNise** [Refaltor77/CustomItemAPI#16]
![Screenshot_2022-03-19-05-50-26-744_com mojang minecraftpe](https://user-images.githubusercontent.com/90197402/159094606-c09aed0f-3dd1-4d18-a6c9-e10a5ee7c95c.jpg)

the config armor groups is correct

pure_netherite_boots:
    type: armor
    name: pure_netherite_boots
    id: 1004
    meta: 0
    armor_group: boots
    texture_path: pure_netherite_boots
    max_durability: 375
    defense_points: 2

**Comment by Refaltor77** [comment]
use the last version please

**Comment by ItsRealNise** [comment]
> use the last version please

thats new version

**Comment by Refaltor77** [comment]
2.3.6 ?

Because, this version was tested and work for the armor slots
