### ISSUE TITLE
aide moi

### ISSUE THREAD

**Issue by pierrickjcp** [Refaltor77/CustomItemAPI#20]
peux tu m'aider je ne comprend rien a ton wiki stp

**Comment by SixpennyYard** [comment]
Je peux t'aider pour les texture si tu veux. 
Mais logiquement tout est expliquer ou en tout cas dans le fichier 'ExampleRS'

**Comment by Refaltor77** [comment]
https://github.com/Refaltor77/CustomItemAPI/tree/main/ExampleRS
