### ISSUE TITLE
Bug Interact avec BasicItem

### ISSUE THREAD

**Issue by SixpennyYard** [Refaltor77/CustomItemAPI#29]
Bonjour,
J'ai un problème avec mon BasicItem quand je clique (droit ou gauche) dans l'air cela ne fais rien et quand je clique sur un block cela me fais crash. 
J'ai fais du copié collé du wiki pourtant ._.

Code:
```
$item = new BasicItem(new ItemIdentifier(1000,0),"test", "test",16);
$item->setInteractListener(function(Player $player, Block $replace, Block $clicked, int $face, Vector3 $clickVector, Item $item): {

   $player->sendMessage("You’re interacting with your item !");
});
$item->addToServer();
```

PS: Je tiens a dire aussi que les ":" de "[...] Item $item): {" font crash le plugin et que je les ai donc enlevé dans mon code.

**Comment by Refaltor77** [comment]
And error in the console please ?

**Comment by Refaltor77** [comment]
Mais c'est normal.... :void faut mettre, c'est de la syntaxe PHP la

**Comment by Refaltor77** [comment]
Je modifierais le wiki mdr

>

**Comment by Refaltor77** [comment]
T'as version de pocketmine stp

**Comment by SixpennyYard** [comment]
La derniere: 4.3.0

**Comment by Refaltor77** [comment]
Faut je fasse un patch car ce bug vien naturellement de PocketMine mais bon il se décide pas a le fix ducoup je vais ajouter un patch bientot
