### ISSUE TITLE
Bug Duplication

### ISSUE THREAD

**Issue by xodamcm** [Refaltor77/CustomItemAPI#38]
Bonjour, j’ai trouvé un bug de duplication,
Il consiste à, prendre une pioche, l’enchanter, efficiency, pour qu’elle soit assez rapide pour causer des degats de chutes quand on creuse en dessous de sois, et lorsqu’on meurt, environ une fois sur deux en aillant effectué plusieurs test, l’item se duplique, j’envoi une vidéo afin que vous puissiez comprendre plus facilement

https://youtu.be/1mrGd6LKGyM

test effectué avec 3 plugins (Hammer, Devtools, CustomItemAPI)

**Comment by Refaltor77** [comment]
Bien vu bg, je fix sa dès que je peux

**Comment by xodamcm** [comment]
Okok super :) ! 👌

**Comment by Refaltor77** [comment]
C'est fix !

**Comment by xodamcm** [comment]
Merci beaucoup !!
Est ce que tu saurais d’ou provient ce crash? Parce qu’il le semble que j’utilisais la dev 47 ou un truc comme sa avant mais avec celle ci j’ai ce crash

Error: Unmapped ID/metadata combination 1203:0
File: pmsrc/src/network/mcpe/convert/ItemTranslator
Line: 168
Type: InvalidArgumentException
Backtrace:
#0 pmsrc/src/network/mcpe/convert/TypeConverter(122): pocketmine\network\mcpe\convert\ItemTranslator->toNetworkId(int 1203, int 0)
#1 pmsrc/src/network/mcpe/cache/CraftingDataCache(106): pocketmine\network\mcpe\convert\TypeConverter->coreItemStackToRecipeIngredient(object pocketmine\item\Item#152147)
#2 pmsrc/src/network/mcpe/cache/CraftingDataCache(67): pocketmine\network\mcpe\cache\CraftingDataCache->buildCraftingDataCache(object pocketmine\crafting\CraftingManager#321)
#3 pmsrc/src/network/mcpe/handler/PreSpawnPacketHandler(124): pocketmine\network\mcpe\cache\CraftingDataCache->getCache(object pocketmine\crafting\CraftingManager#321)
#4 pmsrc/src/network/mcpe/NetworkSession(319): pocketmine\network\mcpe\handler\PreSpawnPacketHandler->setUp()
#5 pmsrc/src/network/mcpe/NetworkSession(697): pocketmine\network\mcpe\NetworkSession->setHandler(object pocketmine\network\mcpe\handler\PreSpawnPacketHandler#136934)
#6 pmsrc/src/network/mcpe/NetworkSession(270): pocketmine\network\mcpe\NetworkSession->beginSpawnSequence()
#7 pmsrc/src/promise/Promise(45): pocketmine\network\mcpe\NetworkSession->onPlayerCreated(object pocketmine\player\Player#136974)
#8 pmsrc/src/network/mcpe/NetworkSession(234): pocketmine\promise\Promise->onCompletion(object Closure#135424, object Closure#135410)
#9 pmsrc/src/network/mcpe/NetworkSession(692): pocketmine\network\mcpe\NetworkSession->createPlayer()
#10 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(142): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#11 pmsrc/vendor/pocketmine/bedrock-protocol/src/ResourcePackClientResponsePacket(61): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#135421)
#12 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler#135414)
#13 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket#135421, string[4] ....)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
#15 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[16] .......Q......,,)
#16 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#130310)
#17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#19 pmsrc/src/Server(1663): pocketmine\snooze\SleeperHandler->sleepUntil(float 1654443201.9945)
#20 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
#21 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#22 pmsrc/src/PocketMine(327): pocketmine\server()
#23 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[159] 		return null;
[160] 	}
[161] 
[162] 	/**
[163] 	 * @return int[]
[164] 	 * @phpstan-return array{int, int}
[165] 	 */
[166] 	public function toNetworkId(int $internalId, int $internalMeta) : array{
[167] 		return $this->toNetworkIdQuiet($internalId, $internalMeta) ??
[168] 			throw new \InvalidArgumentException("Unmapped ID/metadata combination $internalId:$internalMeta");
[169] 	}
[170] 
[171] 	/**
[172] 	 * @return int[]
[173] 	 * @phpstan-return array{int, int}
[174] 	 * @throws TypeConversionException
[175] 	 */
[176] 	public function fromNetworkId(int $networkId, int $networkMeta, ?bool &$isComplexMapping = null) : array{
[177] 		if(isset($this->complexNetToCoreMapping[$networkId])){
[178] 			if($networkMeta !== 0){

**Comment by Refaltor77** [comment]
cela vien surement d'un plugin customCraft

**Comment by xodamcm** [comment]
Yes effectivement, c’est du au plugin Create-DelCraft HiroTeam, il y aurait moyen d’effectuer une compatibilité des deux plugins? (Quelques devs en arrière, les deux fonctionnent ensemble)
