### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by vkamz597** [Refaltor77/CustomItemAPI#41]
ArgumentCountError: "Too few arguments to function refaltor\customitemapi\items\BaseItem::__construct(), 4 passed in /root/pm/plugins/CustomItemLoader.php on line 35 and exactly 5 expected" (EXCEPTION) in "plugins/CustomItemAPI (1).phar/src/refaltor/customitemapi/items/BaseItem" at line 41
--- Stack trace ---
  #0 plugins/CustomItemLoader(35): refaltor\customitemapi\items\BaseItem->__construct(object pocketmine\item\ItemIdentifier#28956, string[15] ..............., string[15] ..............., i

The source code changed when I changed the version to 3.0.1 version, so I changed it accordingly, but this error occurs

**Comment by Refaltor77** [comment]
check args in code
