### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xodamcm** [Refaltor77/CustomItemAPI#42]
Error: Class "refaltor\customitemapi\items\CustomArmor" not found
File: plugins/CustomItemAPI_dev-54.phar/src/refaltor/customitemapi/traits/UtilsTrait
Line: 234
Type: Error
Backtrace:
#0 plugins/CustomItemAPI_dev-54.phar/src/refaltor/customitemapi/CustomItemAPI(59): refaltor\customitemapi\CustomItemAPI->loadConfigurationFiles()
#1 pmsrc/src/plugin/PluginBase(75): refaltor\customitemapi\CustomItemAPI->onLoad()
#2 pmsrc/src/plugin/PluginManager(213): pocketmine\plugin\PluginBase->__construct(object pocketmine\plugin\PharPluginLoader#25751, object pocketmine\Server#10, object pocketmine\plugin\PluginDescription#26158, string[41] /home/container/plugin_data/CustomItemAPI, string[56] phar:///home/container/plugins/CustomItemAPI_dev-54.phar, object pocketmine\plugin\DiskResourceProvider#110736)
#3 pmsrc/src/plugin/PluginManager(362): pocketmine\plugin\PluginManager->internalLoadPlugin(string[49] /home/container/plugins/CustomItemAPI_dev-54.phar, object pocketmine\plugin\PharPluginLoader#25751, object pocketmine\plugin\PluginDescription#26158)
#4 pmsrc/src/Server(1007): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/, int 0)
#5 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#6 pmsrc/src/PocketMine(327): pocketmine\server()
#7 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
Error: Class "refaltor\customitemapi\items\CustomArmor" not found
File: plugins/CustomItemAPI_dev-54.phar/src/refaltor/customitemapi/traits/UtilsTrait
Line: 234
Type: Error
Backtrace:
#0 plugins/CustomItemAPI_dev-54.phar/src/refaltor/customitemapi/CustomItemAPI(59): refaltor\customitemapi\CustomItemAPI->loadConfigurationFiles()
#1 pmsrc/src/plugin/PluginBase(75): refaltor\customitemapi\CustomItemAPI->onLoad()
#2 pmsrc/src/plugin/PluginManager(213): pocketmine\plugin\PluginBase->__construct(object pocketmine\plugin\PharPluginLoader#25751, object pocketmine\Server#10, object pocketmine\plugin\PluginDescription#26158, string[41] /home/container/plugin_data/CustomItemAPI, string[56] phar:///home/container/plugins/CustomItemAPI_dev-54.phar, object pocketmine\plugin\DiskResourceProvider#110736)
#3 pmsrc/src/plugin/PluginManager(362): pocketmine\plugin\PluginManager->internalLoadPlugin(string[49] /home/container/plugins/CustomItemAPI_dev-54.phar, object pocketmine\plugin\PharPluginLoader#25751, object pocketmine\plugin\PluginDescription#26158)
#4 pmsrc/src/Server(1007): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/, int 0)
#5 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#6 pmsrc/src/PocketMine(327): pocketmine\server()
#7 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[225]                 $texture_path = $values['texture_path'];
[226]                 $defense = $values['defense_points'];
[227]                 $durability = $values['durability'] ?? false;
[228]                 $slot = match (strtolower($values['type'])) {
[229]                     'helmet' => ArmorInventory::SLOT_HEAD,
[230]                     'chestplate' => ArmorInventory::SLOT_CHEST,
[231]                     'leggings' => ArmorInventory::SLOT_LEGS,
[232]                     'boots' => ArmorInventory::SLOT_FEET,
[233]                 };
[234]                 $item = new CustomArmor(new ItemIdentifier($id, $meta), $name, new ArmorTypeInfo($defense, $durability, $slot), $texture_path);
[235]                 $arrayQueried[] = $item;
[236]             }
[237]         }
[238]         $this->getAPI()->registerAll($arrayQueried);
[239]         $this->getServer()->getLogger()->debug("[CustomItemAPI] Logs //: configuration files is loaded.");
[240]     }
[241] }

**Comment by Refaltor77** [comment]
Has fix x)
