### ISSUE TITLE
Still Crashed Different Error not CustomArmor things 

### ISSUE THREAD

**Issue by ZexKenden** [Refaltor77/CustomItemAPI#46]
PocketMine-MP Crash Dump Wed Jun 8 17:51:37 UTC 2022

PocketMine-MP version: 4.5.0 [Protocol 527]
Git commit: 64a8c462f933b2e4ac29b918df56113c7767f0be
PHP version: 8.0.17
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CustomItemAPI

Error: refaltor\customitemapi\managers\ItemManager::getPacket(): Return value must be of type pocketmine\network\mcpe\protocol\ItemComponentPacket, null returned
File: plugins/CustomItemAPI.phar/src/refaltor/customitemapi/managers/ItemManager
Line: 143
Type: TypeError
Backtrace:
#0 plugins/CustomItemAPI.phar/src/refaltor/customitemapi/events/listeners/PlayerListeners(48): refaltor\customitemapi\managers\ItemManager->getPacket()
#1 pmsrc/src/event/RegisteredListener(60): refaltor\customitemapi\events\listeners\PlayerListeners->onJoin(object pocketmine\event\player\PlayerJoinEvent#105342)
#2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent#105342)
#3 pmsrc/src/player/Player(834): pocketmine\event\Event->call()
#4 pmsrc/src/network/mcpe/NetworkSession(704): pocketmine\player\Player->doFirstSpawn()
#5 pmsrc/src/network/mcpe/NetworkSession(697): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
#6 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(35): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#7 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#105089)
#8 pmsrc/src/network/mcpe/NetworkSession(388): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#110821)
#9 pmsrc/src/network/mcpe/NetworkSession(351): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#105089, string[2] q.)
#10 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[41] c*d4..............wb`(8...@qF&..`Uz......)
#11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[50] ...m..>....J.s)...g........]q9.8q..D(...r.......QS)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#36184)
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#15 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1654710697.2631)
#16 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#17 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#18 pmsrc/src/PocketMine(327): pocketmine\server()
#19 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[134]                     $this->items[] = $item;
[135]                 } else $this->getPlugin()->getServer()->getLogger()->error("[!] ". $item::class ." Is not custom item.");
[136]             } catch (Exception $exception) {
[137]                 $this->getPlugin()->getServer()->getLogger()->error("[!] ". $item::class ." Is not custom item.");
[138]             }
[139]         }
[140]     }
[141] 
[142]     public function getPacket(): ItemComponentPacket {
[143]         return $this->packet;
[144]     }
[145] 
[146] 
[147]     public function getItemInCache(): array {
[148]         return $this->items;
[149]     }
[150] }

I use lasted version 3.1.1

**Comment by Refaltor77** [comment]
You used the config ?

**Comment by Refaltor77** [comment]
Hey! I fixed the bug, use version 3.2.0
