### ISSUE TITLE
Server shutdown

### ISSUE THREAD

**Issue by xodamcm** [Refaltor77/CustomItemAPI#48]
![C7C2C873-AB8A-4CC0-B801-D89D18E6577B](https://user-images.githubusercontent.com/89165041/172722403-a280b696-cb90-4713-af22-e6d8c616750d.jpeg)
Error: (with customitemapi) failed to load some plugin and server shutdown in dev 59

**Comment by Refaltor77** [comment]
Yes, dev 60 us good, sorry for the crash

**Comment by xodamcm** [comment]
Same on dev 60 ..
