### ISSUE TITLE
Bug un seul item se load par categorie

### ISSUE THREAD

**Issue by xodamcm** [Refaltor77/CustomItemAPI#49]
Salut, sur mon serveur j’ai pas tous les items qui se mettent, je m’explique, j’ai une pioche, un item bouffe, un item normal, une paire de botttes, pourtant da s ma config j’ai plusieurs armures, plusieurs pioches, d’autres outils et items, et les bottes et la pioche ne se mettent aps dans leurs categories (pas important mais je precise)
Voila je sais pas si ca vient de moi mais je penses pas car j’ai réécris ma config de A a Z pour etre sur, en tout cas merci pour tout, depuis plusieurs jours

update, je m’explique un peux mieux, j’ai désactivé la partie qui désactive le plugin a cause de la version 1.0.0 parce que sinon je n’arrive pas a lancer le plugin, les items se load bien mais c’est seulement le dernier item dans la config qui va se load, un item par catégorie, je m’explique,

Si je met une armure test, c’est seulement le dernier items en bas de la config (des armures) qui se load, donc en l’occurence si je cree casque plastron jambières et bottes, seuls les bottes se load, si je met le plastron en dernier, seul le plastron va se load, et pareil pour les autres items, si je mets des outils, seul le derniers outils va se load, pareil pour les items un seul item est capable de se load, le dernier de la config ….. pas trop claire je me répète beaucoup mais ca devrait être compréhensible ^^

**Comment by Refaltor77** [comment]
Alors oui je viens de trouver la cause je patch sa ce soir mais tkt pas les items sont bien tous load faut juste te les give :)

**Comment by Refaltor77** [comment]
Ah nan j'avais pas compris tas requête, je regarde ce soir

**Comment by Refaltor77** [comment]
Envoie moi tas config

**Comment by xodamcm** [comment]
Okok merci encore !

# /!\ do not touch please.
vesion: 3.2.1


# CustomItemAPI configuration v1.0.0.
# CustomItemAPI is a plugin that allows
# to add items to your server.
# The plugin supports:
# ------------------
# - CustomFood
# - CustomPotion (animation)
# - CustomArmor
# - CustomPickaxe
# - CustomShovel
# - CustomHoe
# - CustomAxe
# - CustomSword
# ------------------
# For all requests for assistance
# Discord: Refaltor#6969
# github: https://github.com/refaltor77



basic_items:
  example_basic_item: # This name is used only if the "name" value does not exist.
    name: test # never use space in your item names | required.
    id: 1000 # required
    meta: 0 # optional | default is 0
    texture_path: stick # texture present only in the textures/items folder of your pack | required
    max_stack_size: 16 # optional | default is 64
    allow_off_hand: false # optional | default is false
    
basic_items:
  example_basic_item2: # This name is used only if the "name" value does not exist.
    name: test2 # never use space in your item names | required.
    id: 1001 # required
    meta: 0 # optional | default is 0
    texture_path: stick # texture present only in the textures/items folder of your pack | required
    max_stack_size: 16 # optional | default is 64
    allow_off_hand: false # optional | default is false

food_items:
  example_food_item:
    name: test_food # Always use "_" for spaces.
    id: 1002 # required
    meta: 0 # optional | default is 0
    is_potion: false # if true, The animation of eating will be like a potion. | optional default is false
    texture_path: apple # required
    max_stack_size: 32 # optional | default is 64
    can_always_eat: true # This allows you to always eat the item even if the player is not hungry | optional default is false
    food_restore: 4 # use only integer numbers for this value. | required
    saturation_restore: 15.0 # use only float numbers for this value. | required
    
food_items:
  example_food_item:
    name: test_food # Always use "_" for spaces.
    id: 1003 # required
    meta: 0 # optional | default is 0
    is_potion: false # if true, The animation of eating will be like a potion. | optional default is false
    texture_path: apple # required
    max_stack_size: 32 # optional | default is 64
    can_always_eat: true # This allows you to always eat the item even if the player is not hungry | optional default is false
    food_restore: 4 # use only integer numbers for this value. | required
    saturation_restore: 15.0 # use only float numbers for this value. | required
    
tool_items:
  example_tool:
    name: test_pickaxe
    id: 1004
    meta: 0
    type: pickaxe # pickaxe | axe | shovel | sword | hoe - required
    tier: diamond # diamond | golden | iron | stone | wooden - required
    texture_path: apple # required
    mining_speed: 3.0 # use only float numbers for this value. | required
    durability: 100 # required
    attack_point: 2 # required
    
tool_items:
  example_tool2:
    name: test_sword
    id: 1005
    meta: 0
    type: sword # pickaxe | axe | shovel | sword | hoe - required
    tier: diamond # diamond | golden | iron | stone | wooden - required
    texture_path: apple # required
    mining_speed: 3.0 # use only float numbers for this value. | required
    durability: 100 # required
    attack_point: 2 # required

armor_items:
  example_helmet:
    name: test_helmet
    id: 1006
    meta: 0
    type: helmet # helmet | chestplate | leggings | boots - required
    texture_path: iron_helmet
    defense_points: 5 # required
    durability: 500 # required
    
armor_items:
  example_chestplate:
    name: test_chestplate
    id: 1007
    meta: 0
    type: chestplate # helmet | chestplate | leggings | boots - required
    texture_path: iron_chestplate
    defense_points: 5 # required
    durability: 500 # required

c’est chaque fois l’item 2 de chaque categorie qui se load, je peux pas me give les autres 

par exemple avec cette config c’est

l’item exemple 2, litem food 2, l’epee, et le plastron, qui se load, le reste se load pas apparement (item exemple1, item food1, la pioche, et le casque)

**Comment by Refaltor77** [comment]
Envoie t'as config en fichier stp car la je voit pas l'indentation

**Comment by Refaltor77** [comment]
J'ai essayer un truc dans la dernier version de CustomItem, essaie pour voir avec la 3.2.3

**Comment by xodamcm** [comment]
apparemment( c'est toujours pareil.. je send ma config en fichier du cou
[config.txt](https://github.com/Refaltor77/CustomItemAPI/files/8873033/config.txt)
p

**Comment by Refaltor77** [comment]
Enfaite, dans "tool_items" faut mettre tout tes items et par re crée un "tool_items"

**Comment by xodamcm** [comment]
Ptdr jsuis un gros mongolien ! Merci beaucoup
