### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Willtom999** [Refaltor77/CustomItemAPI#50]
![8B748505-49D2-42D1-993D-CEE45CD30FB2](https://user-images.githubusercontent.com/83521998/172871256-44339b4c-17dc-48cd-b985-e29519d6832f.jpeg)
![160186C2-2F72-4C80-AC1E-20ACD66E9326](https://user-images.githubusercontent.com/83521998/172871405-9ca82601-9fc4-4842-8b66-85ab748ca884.png)

**Comment by Refaltor77** [comment]
Fix with 3.2.3

**Comment by Willtom999** [comment]
Encore bug

**Comment by Willtom999** [comment]
![Uploading E35D9C82-662A-4CDD-9240-22DFD01961DB.jpeg…]()
