### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xodamcm** [Refaltor77/CustomItemAPI#54]
Salut, j’arrive plus a me give les items par id, et par nom d’item.. 

Ex:
/give @s test 
/give @s 9999
marchent pas, pourtant les items sont bien load

et j’ai remarqué aussi que les items customs: 
Basic, et Armures, s’appellent item.custom:nomdelitem

et les items customs: Food, et Outils
item.nomdeltitem

et egalement les armures ne peuvent pas etre enchant, mais les outils peuvent

**Comment by Refaltor77** [comment]
Sa c'est pocketmine, pour les enchant des armures je suis sur le coup

**Comment by xodamcm** [comment]
Okok au top tu gères!! 👌

**Comment by Refaltor77** [comment]
Les armures peuvent enfin etre enchanté !

Pour le nom des items, tu doit les renommé dans le pack dans ton tas_langue.lang en faisant item.nom_de_litem.name=Mon item wow !

Pour le /give je suis very sorry c'est pocketmine x) mais après vanillaX a recodé le /give et tu peux te les give en faisant /give custom:ton_item

**Comment by xodamcm** [comment]
Merci pour tout !!!! Juste pour les armures, moi sa bug encore, mais ca vient peut etre de VanillaX

**Comment by xodamcm** [comment]
Aparrement non, je peux toujours pas ..

**Comment by Refaltor77** [comment]
tu utilise vanillaX pour tes enchants ? et genre sa t'affiche rien dans la table ?

**Comment by Refaltor77** [comment]
Car de mon coté tout fonctionne, assure toi d'avoir la dernier version de CustomItemAPI

**Comment by xodamcm** [comment]
Si effectivement les enchant s’affichent bien tu as raison, le problème ne vient pas de CustomItemAPI ca doit venir du cote de VanillaX, désolé de t’avoir fais perdre du temps.. et merci encore 😊

**Comment by Refaltor77** [comment]
Nickel ! tkt, je close
