### ISSUE TITLE
Error with new pmmp 4.17

### ISSUE THREAD

**Issue by Fuzuto** [Refaltor77/CustomItemAPI#62]
some error with pmmp 4.17

![image](https://user-images.githubusercontent.com/52622140/225519489-4b8d8a5f-4c64-46f9-976d-f5683ee5d33a.png)

**Comment by Refaltor77** [comment]
Error fixed in New update !

**Comment by WanterPro** [comment]
But now how to create items

**Comment by WanterPro** [comment]
Can i get your discord add me Wanter#0007
