### ISSUE TITLE
what is this do i need to care about it and if edit what should i edit when i create new item

### ISSUE THREAD

**Issue by TienDat2k** [Refaltor77/CustomItemAPI#9]
![image](https://user-images.githubusercontent.com/88370821/155151505-62d250a6-ea4b-4a04-b8a5-3a37652ae000.png)

**Comment by TienDat2k** [comment]
I'm a newbie not a coder so I don't understand please explain

**Comment by ByLex-69bits** [comment]
its for the texture. if u are not a dev just use the basic config. 
example:
astral_basic_item:
    type: basic
    name: astral
    id: 3001 
    meta: 0
    max_stack_size: 16
    texture_path: blaze_powder

here u have a basic item. So don't touch the manifest.json. Btw the file who is open on ur screen don't touch it.

**Comment by Refaltor77** [comment]
You must create the name of you have texture in "item_texture.json" present in the pack
